local ui_reference = ui.reference
local ui_set_visible = ui.set_visible
local ui_get = ui.get
local ui_set = ui.set
local client_log = client.log

local isCopiedAA, isCopiedESP = 0, 0

-- ESP Start

local teammates =  ui_reference("VISUALS", "Player ESP", "Teammates")
local dormant = ui_reference("VISUALS", "Player ESP", "Dormant")
local bounding_box, bounding_box_color = ui_reference("VISUALS", "Player ESP", "Bounding box")
local health_bar = ui_reference("VISUALS", "Player ESP", "Health bar")
local name, name_color = ui_reference("VISUALS", "Player ESP", "Name")
local flags = ui_reference("VISUALS", "Player ESP", "Flags")
local weapon = ui_reference("VISUALS", "Player ESP", "Weapon text")
local weapon_icon, weapon_icon_color = ui_reference("VISUALS", "Player ESP", "Weapon icon")
local ammo, ammo_color = ui_reference("VISUALS", "Player ESP", "Ammo")
local distance = ui_reference("VISUALS", "Player ESP", "Distance")
local lby_timer, lby_timer_color = ui_reference("VISUALS", "Player ESP", "LBY timer")
local glow, glow_color = ui_reference("VISUALS", "Player ESP", "Glow")
local hit_marker = ui_reference("VISUALS", "Player ESP", "Hit marker")
local hit_marker_sound = ui_reference("VISUALS", "Player ESP", "Hit marker sound")
local visualize_sounds, visualize_sounds_color = ui_reference("VISUALS", "Player ESP", "Visualize sounds")
local line_of_sight, line_of_sight_color = ui_reference("VISUALS", "Player ESP", "Line of sight")
local money = ui_reference("VISUALS", "Player ESP", "Money")
local skeleton, skeleton_color = ui_reference("VISUALS", "Player ESP", "Skeleton")
local out_of_fov_arrow, out_of_fov_arrow_color, out_of_fov_arrow_size, out_of_fov_arrow_distance = ui_reference("VISUALS", "Player ESP", "Out of FOV arrow")
local player, player_color = ui_reference("VISUALS", "Colored models", "Player")
local player_behind_wall, player_behind_wall_color = ui_reference("VISUALS", "Colored models", "Player behind wall")
local reflectivity_slider, reflectivity_color = ui_reference("VISUALS", "Colored models", "Reflectivity")
local shine_slider = ui_reference("VISUALS", "Colored models", "Shine")
local rim_slider = ui_reference("VISUALS", "Colored models", "Rim")
local show_teammates, show_teammates_color = ui_reference("VISUALS", "Colored models", "Show teammates")
local disable_model_occlusion = ui_reference("VISUALS", "Colored models", "Disable model occlusion")
local shadow, shadow_color = ui_reference("VISUALS", "Colored models", "Shadow")

local radar = ui_reference("VISUALS", "Other ESP", "Radar")
local dropped_weapons_combobox, dropped_weapons_color = ui_reference("VISUALS", "Other ESP", "Dropped weapons")
local dropped_weapon_ammo = ui_reference("VISUALS", "Other ESP", "Dropped weapon ammo")
local grenades, grenades_color = ui_reference("VISUALS", "Other ESP", "Grenades")
local inaccuracy_overlay, inaccuracy_overlay_color = ui_reference("VISUALS", "Other ESP", "Inaccuracy overlay")
local recoil_overlay = ui_reference("VISUALS", "Other ESP", "Recoil overlay")
local crosshair = ui_reference("VISUALS", "Other ESP", "Crosshair")
local bomb, bomb_color = ui_reference("VISUALS", "Other ESP", "Bomb")
local grenade_trajectory = ui_reference("VISUALS", "Other ESP", "Grenade trajectory")
local spectators = ui_reference("VISUALS", "Other ESP", "Spectators")
local penetration_reticle = ui_reference("VISUALS", "Other ESP", "Penetration reticle")
local hostages, hostages_color = ui_reference("VISUALS", "Other ESP", "Hostages")
local shared_esp = ui_reference("VISUALS", "Other ESP", "Shared ESP")
local shared_esp_with_other_team = ui_reference("VISUALS", "Other ESP", "Shared ESP with other team")
local restrict_shared_esp_updates = ui_reference("VISUALS", "Other ESP", "Restrict shared ESP updates")
local remove_flashbang_effects = ui_reference("VISUALS", "Effects", "Remove flashbang effects")
local remove_smoke_grenades = ui_reference("VISUALS", "Effects", "Remove smoke grenades")
local remove_fog = ui_reference("VISUALS", "Effects", "Remove fog")
local visual_recoil_adjustment = ui_reference("VISUALS", "Effects", "Visual recoil adjustment")
local transparent_walls = ui_reference("VISUALS", "Effects", "Transparent walls")
local transparent_props = ui_reference("VISUALS", "Effects", "Transparent props")
local brightness_adjustment = ui_reference("VISUALS", "Effects", "Brightness adjustment")
local remove_scope_overlay = ui_reference("VISUALS", "Effects", "Remove scope overlay")
local instant_scope = ui_reference("VISUALS", "Effects", "Instant scope")
local disable_post_processing = ui_reference("VISUALS", "Effects", "Disable post processing")
local force_third_person_alive = ui_reference("VISUALS", "Effects", "Force third person (alive)")
local force_third_person_dead = ui_reference("VISUALS", "Effects", "Force third person (dead)")
local disable_rendering_of_teammates = ui_reference("VISUALS", "Effects", "Disable rendering of teammates")
local bullet_tracers, bullet_tracers_color = ui_reference("VISUALS", "Effects", "Bullet tracers")
local bullet_impacts, bullet_impacts_time = ui_reference("VISUALS", "Effects", "Bullet impacts")

-- Anti-aims Start

local pitch = ui.reference("AA", "Anti-aimbot angles", "Pitch")
local yawbase = ui.reference("AA", "Anti-aimbot angles", "Yaw base")
local yaw, yawnum = ui.reference("AA", "Anti-aimbot angles", "Yaw")
local yawjitter, yawjitternum = ui.reference("AA", "Anti-aimbot angles", "Yaw jitter")
local yawwhilerunning, yawwhilerunningnum = ui.reference("AA", "Anti-aimbot angles", "Yaw while running")
local fakeyaw, fakeyawnum = ui.reference("AA", "Anti-aimbot angles", "Fake yaw")
local edgeyaw = ui.reference("AA", "Anti-aimbot angles", "Edge yaw")
local freestanding = ui.reference("AA", "Anti-aimbot angles", "Freestanding")
local freestanding_real_yawnum = ui.reference("AA", "Anti-aimbot angles", "Freestanding real yaw offset")
local freestanding_fake_yawnum = ui.reference("AA", "Anti-aimbot angles", "Freestanding fake yaw offset")
local freestanding_ignoreduck = ui.reference("AA", "Anti-aimbot angles", "Freestanding ignore duck")
local crooked = ui.reference("AA", "Anti-aimbot angles", "Crooked")
local twist = ui.reference("AA", "Anti-aimbot angles", "Twist")
local fakelag_enabled = ui.reference("AA", "Fake lag", "Enabled")
local fakelag_triggers = ui.reference("AA", "Fake lag", "Triggers")
local fakelag_amount = ui.reference("AA", "Fake lag", "Amount")
local fakelag_variance = ui.reference("AA", "Fake lag", "Variance")
local fakelag_limit = ui.reference("AA", "Fake lag", "Limit")
local fakelag_whileshooting = ui.reference("AA", "Fake lag", "Fake lag while shooting")
local fakelag_resetonbhop = ui.reference("AA", "Fake lag", "Reset on bunny hop")
local fakelag_resetonstandstill = ui.reference("AA", "Fake lag", "Reset on standstill")
local slowmotion = ui.reference("AA", "Other", "Slow motion")
local fixlegmovement = ui.reference("AA", "Other", "Fix leg movement")

-- Anti-aims End

function CopyVisuals()
	teammates_value = ui_get(teammates)
	dormant_value = ui_get(dormant)
	bounding_box_value = ui_get(bounding_box)
	bounding_box_color_r_value, bounding_box_color_g_value, bounding_box_color_b_value, bounding_box_color_a_value = ui_get(bounding_box_color)
	health_bar_value = ui_get(health_bar)
	name_value = ui_get(name)
	name_color_r_value, name_color_g_value, name_color_b_value, name_color_a_value = ui_get(name_color)
	flags_value = ui_get(flags)
	weapon_value = ui_get(weapon)
	weapon_icon_value = ui_get(weapon_icon)
	weapon_icon_color_r_value, weapon_icon_color_g_value, weapon_icon_color_b_value, weapon_icon_color_a_value = ui_get(weapon_icon_color)
	ammo_value = ui_get(ammo)
	ammo_color_r_value, ammo_color_g_value, ammo_color_b_value, ammo_color_a_value = ui_get(ammo_color)
	distance_value = ui_get(distance)
	lby_timer_value = ui_get(lby_timer)
	lby_timer_color_r_value, lby_timer_color_g_value, lby_timer_color_b_value, lby_timer_color_a_value = ui_get(lby_timer_color)
	glow_value = ui_get(glow)
	glow_color_r_value, glow_color_g_value, glow_color_b_value, glow_color_a_value = ui_get(glow_color)
	hit_marker_value = ui_get(hit_marker)
	hit_marker_sound_value = ui_get(hit_marker_sound)
	visualize_sounds_value = ui_get(visualize_sounds)
	visualize_sounds_color_r_value, visualize_sounds_color_g_value, visualize_sounds_color_b_value, visualize_sounds_color_a_value = ui_get(visualize_sounds_color)
	line_of_sight_value = ui_get(line_of_sight)
	line_of_sight_color_r_value, line_of_sight_color_g_value, line_of_sight_color_b_value, line_of_sight_color_a_value = ui_get(line_of_sight_color)
	money_value = ui_get(money)
	skeleton_value = ui_get(skeleton)
	skeleton_color_r_value, skeleton_color_g_value, skeleton_color_b_value, skeleton_color_a_value = ui_get(skeleton_color)
	out_of_fov_arrow_value = ui_get(out_of_fov_arrow)
	out_of_fov_arrow_color_r_value, out_of_fov_arrow_color_g_value, out_of_fov_arrow_color_b_value, out_of_fov_arrow_color_a_value = ui_get(out_of_fov_arrow_color)
	out_of_fov_arrow_size_value = ui_get(out_of_fov_arrow_size)
	out_of_fov_arrow_distance_value = ui_get(out_of_fov_arrow_distance)
	player_value = ui_get(player)
	player_color_r_value, player_color_g_value, player_color_b_value, player_color_a_value = ui_get(player_color)
	player_behind_wall_value = ui_get(player_behind_wall)
	player_behind_wall_color_r_value, player_behind_wall_color_g_value, player_behind_wall_color_b_value, player_behind_wall_color_a_value = ui_get(player_behind_wall_color)
	reflectivity_slider_value = ui_get(reflectivity_slider)
	reflectivity_color_r_value, reflectivity_color_g_value, reflectivity_color_b_value, reflectivity_color_a_value = ui_get(reflectivity_color)
	shine_slider_value = ui_get(shine_slider)
	rim_slider_value = ui_get(rim_slider)
	show_teammates_value = ui_get(show_teammates)
	show_teammates_color_r_value, show_teammates_color_g_value, show_teammates_color_b_value, show_teammates_color_a_value = ui_get(show_teammates_color)
	disable_model_occlusion_value = ui_get(disable_model_occlusion)
	shadow_value = ui_get(shadow)
	shadow_color_r_value, shadow_color_g_value, shadow_color_b_value, shadow_color_a_value = ui_get(player)
	CopyVisuals_2()
end

function CopyVisuals_2()
	radar_value = ui_get(radar)
	dropped_weapons_combobox_value = ui_get(dropped_weapons_combobox)
	dropped_weapons_color_r_value, dropped_weapons_color_g_value, dropped_weapons_color_b_value, dropped_weapons_color_a_value = ui_get(dropped_weapons_color)
	dropped_weapon_ammo_value = ui_get(dropped_weapon_ammo)
	grenades_value = ui_get(grenades)
	grenades_color_r_value, grenades_color_g_value, grenades_color_b_value, grenades_color_a_value = ui_get(grenades_color)
	inaccuracy_overlay_value = ui_get(inaccuracy_overlay)
	inaccuracy_overlay_color_r_value, inaccuracy_overlay_color_g_value, inaccuracy_overlay_color_b_value, inaccuracy_overlay_color_a_value = ui_get(inaccuracy_overlay_color)
	recoil_overlay_value = ui_get(recoil_overlay)
	crosshair_value = ui_get(crosshair)
	bomb_value = ui_get(bomb)
	bomb_color_r_value, bomb_color_g_value, bomb_color_b_value, bomb_color_a_value = ui_get(bomb_color)
	grenade_trajectory_value = ui_get(grenade_trajectory)
	spectators_value = ui_get(spectators)
	penetration_reticle_value = ui_get(penetration_reticle)
	hostages_value = ui_get(hostages)
	hostages_color_r_value, hostages_color_g_value, hostages_color_b_value, hostages_color_a_value = ui_get(hostages_color)
	shared_esp_value = ui_get(shared_esp)
	shared_esp_with_other_team_value = ui_get(shared_esp_with_other_team)
	restrict_shared_esp_updates_value = ui_get(restrict_shared_esp_updates)
	remove_flashbang_effects_value = ui_get(remove_flashbang_effects)
	remove_smoke_grenades_value = ui_get(remove_smoke_grenades)
	remove_fog_value = ui_get(remove_fog)
	visual_recoil_adjustment_value = ui_get(visual_recoil_adjustment)
	transparent_walls_value = ui_get(transparent_walls)
	transparent_props_value = ui_get(transparent_props)
	brightness_adjustment_value = ui_get(brightness_adjustment)
	remove_scope_overlay_value = ui_get(remove_scope_overlay)
	instant_scope_value = ui_get(instant_scope)
	disable_post_processing_value = ui_get(disable_post_processing)
	force_third_person_alive_value = ui_get(force_third_person_alive)
	force_third_person_dead_value = ui_get(force_third_person_dead)
	disable_rendering_of_teammates_value = ui_get(disable_rendering_of_teammates)
	bullet_tracers_value = ui_get(bullet_tracers)
	bullet_tracers_color_r_value, bullet_tracers_color_g_value, bullet_tracers_color_b_value, bullet_tracers_color_a_value = ui_get(bullet_tracers_color)
	bullet_impacts_value = ui_get(bullet_impacts)
	bullet_impacts_time_value = ui_get(bullet_impacts_time)

	isCopiedESP = 1
	client_log("Visuals: Coppied successfully!")
 end

function MoveVisuals()
	ui_set(teammates, teammates_value)
	ui_set(dormant, dormant_value)
	ui_set(bounding_box, bounding_box_value)
	ui_set(bounding_box_color, bounding_box_color_r_value, bounding_box_color_g_value, bounding_box_color_b_value, bounding_box_color_a_value)
	ui_set(health_bar, health_bar_value)
	ui_set(name, name_value)
	ui_set(name_color, name_color_r_value, name_color_g_value, name_color_b_value, name_color_a_value)
	ui_set(flags, flags_value)
	ui_set(weapon, weapon_value)
	ui_set(weapon_icon, weapon_icon_value)
	ui_set(weapon_icon_color, weapon_icon_color_r_value, weapon_icon_color_g_value, weapon_icon_color_b_value, weapon_icon_color_a_value)
	ui_set(ammo, ammo_value)
	ui_set(ammo_color, ammo_color_r_value, ammo_color_g_value, ammo_color_b_value, ammo_color_a_value)
	ui_set(distance, distance_value)
	ui_set(lby_timer, lby_timer_value)
	ui_set(lby_timer_color, lby_timer_color_r_value, lby_timer_color_g_value, lby_timer_color_b_value, lby_timer_color_a_value)
	ui_set(glow, glow_value)
	ui_set(glow_color, glow_color_r_value, glow_color_g_value, glow_color_b_value, glow_color_a_value)
	ui_set(hit_marker, hit_marker_value)
	ui_set(hit_marker_sound, hit_marker_sound_value)
	ui_set(visualize_sounds, visualize_sounds_value)
	ui_set(visualize_sounds_color, visualize_sounds_color_r_value, visualize_sounds_color_g_value, visualize_sounds_color_b_value, visualize_sounds_color_a_value)
	ui_set(line_of_sight, line_of_sight_value)
	ui_set(line_of_sight_color, line_of_sight_color_r_value, line_of_sight_color_g_value, line_of_sight_color_b_value, line_of_sight_color_a_value)
	ui_set(money, money_value)
	ui_set(skeleton, skeleton_value)
	ui_set(skeleton_color, skeleton_color_r_value, skeleton_color_g_value, skeleton_color_b_value, skeleton_color_a_value)
	ui_set(out_of_fov_arrow, out_of_fov_arrow_value)
	ui_set(out_of_fov_arrow_color, out_of_fov_arrow_color_r_value, out_of_fov_arrow_color_g_value, out_of_fov_arrow_color_b_value, out_of_fov_arrow_color_a_value)
	ui_set(out_of_fov_arrow_size, out_of_fov_arrow_size_value)
	ui_set(out_of_fov_arrow_distance, out_of_fov_arrow_distance_value)
	ui_set(player, player_value)
	ui_set(player_color, player_color_r_value, player_color_g_value, player_color_b_value, player_color_a_value)
	ui_set(player_behind_wall, player_behind_wall_value)
	ui_set(player_behind_wall_color, player_behind_wall_color_r_value, player_behind_wall_color_g_value, player_behind_wall_color_b_value, player_behind_wall_color_a_value)
	ui_set(reflectivity_slider,  reflectivity_slider_value)
	ui_set(reflectivity_color, reflectivity_color_r_value, reflectivity_color_g_value, reflectivity_color_b_value, reflectivity_color_a_value)
	ui_set(shine_slider, shine_slider_value)
	ui_set(rim_slider, rim_slider_value)
	ui_set(show_teammates, show_teammates_value)
	ui_set(show_teammates_color, show_teammates_color_r_value, show_teammates_color_g_value, show_teammates_color_b_value, show_teammates_color_a_value)
	ui_set(disable_model_occlusion, disable_model_occlusion_value)
	ui_set(shadow, shadow_value)
	ui_set(player, shadow_color_r_value, shadow_color_g_value, shadow_color_b_value, shadow_color_a_value)
	
	MoveVisuals_2()
end

function MoveVisuals_2()
	ui_set(radar, radar_value)
	ui_set(dropped_weapons_combobox, dropped_weapons_combobox_value)
	ui_set(dropped_weapons_color, dropped_weapons_color_r_value, dropped_weapons_color_g_value, dropped_weapons_color_b_value, dropped_weapons_color_a_value)
	ui_set(dropped_weapon_ammo, dropped_weapon_ammo_value)
	ui_set(grenades, grenades_value)
	ui_set(grenades_color, grenades_color_r_value, grenades_color_g_value, grenades_color_b_value, grenades_color_a_value)
	ui_set(inaccuracy_overlay, inaccuracy_overlay_value)
	ui_set(inaccuracy_overlay_color, inaccuracy_overlay_color_r_value, inaccuracy_overlay_color_g_value, inaccuracy_overlay_color_b_value, inaccuracy_overlay_color_a_value)
	ui_set(recoil_overlay, recoil_overlay_value)
	ui_set(crosshair, crosshair_value)
	ui_set(bomb, bomb_value)
	ui_set(bomb_color, bomb_color_r_value, bomb_color_g_value, bomb_color_b_value, bomb_color_a_value)
	ui_set(grenade_trajectory, grenade_trajectory_value)
	ui_set(spectators, spectators_value)
	ui_set(penetration_reticle, penetration_reticle_value)
	ui_set(hostages, hostages_value)
	ui_set(hostages_color, hostages_color_r_value, hostages_color_g_value, hostages_color_b_value, hostages_color_a_value)
	ui_set(shared_esp, shared_esp_value)
	ui_set(shared_esp_with_other_team, shared_esp_with_other_team_value)
	ui_set(restrict_shared_esp_updates, restrict_shared_esp_updates_value)
	ui_set(remove_flashbang_effects, remove_flashbang_effects_value)
	ui_set(remove_smoke_grenades, remove_smoke_grenades_value)
	ui_set(remove_fog, remove_fog_value)
	ui_set(visual_recoil_adjustment, visual_recoil_adjustment_value)
	ui_set(transparent_walls, transparent_walls_value)
	ui_set(transparent_props, transparent_props_value)
	ui_set(brightness_adjustment, brightness_adjustment_value)
	ui_set(remove_scope_overlay, remove_scope_overlay_value)
	ui_set(instant_scope, instant_scope_value)
	ui_set(disable_post_processing, disable_post_processing_value)
	ui_set(force_third_person_alive, force_third_person_alive_value)
	ui_set(force_third_person_dead, force_third_person_dead_value)
	ui_set(disable_rendering_of_teammates, disable_rendering_of_teammates_value)
	ui_set(bullet_tracers, bullet_tracers_value)
	ui_set(bullet_tracers_color, bullet_tracers_color_r_value, bullet_tracers_color_g_value, bullet_tracers_color_b_value, bullet_tracers_color_a_value)
	ui_set(bullet_impacts, bullet_impacts_value)
	ui_set(bullet_impacts_time, bullet_impacts_time_value)
	
	client_log("Visuals: Pasted successfully!")
end

-- Anti-aims Start

local function CopyAA()
	pitch_value = ui.get(pitch)
	yawbase_value = ui.get(yawbase)
	yaw_value = ui.get(yaw)
	yawnum_value = ui.get(yawnum)
	yawjitter_value = ui.get(yawjitter)
	yawjitternum_value = ui.get(yawjitternum)
	yawwhilerunning_value = ui.get(yawwhilerunning)
	yawwhilerunningnum_value = ui.get(yawwhilerunningnum)
	fakeyaw_value = ui.get(fakeyaw)
	fakeyawnum_value = ui.get(fakeyawnum)
	edgeyaw_value = ui.get(edgeyaw)
	freestanding_value = ui.get(freestanding)
	freestanding_real_yawnum_value = ui.get(freestanding_real_yawnum)
	freestanding_fakeyawnum_value = ui.get(freestanding_fake_yawnum)
	freestanding_ignoreduck_value = ui.get(freestanding_ignoreduck)
	crooked_value = ui.get(crooked)
	twist_value = ui.get(twist)
	fakelag_enabled_value = ui.get(fakelag_enabled)
	fakelag_triggers_value = ui.get(fakelag_triggers)
	fakelag_amount_value = ui.get(fakelag_amount)
	fakelag_variance_value = ui.get(fakelag_variance)
	fakelag_limit_value = ui.get(fakelag_limit)
	fakelag_whileshooting_value = ui.get(fakelag_whileshooting)
	fakelag_resetonbhop_value = ui.get(fakelag_resetonbhop)
	fakelag_resetonstandstill_value = ui.get(fakelag_resetonstandstill)
	slowmotion_value = ui.get(slowmotion)
	fixlegmovement_value = ui.get(fixlegmovement)

	isCopiedAA = 1
	client_log("Anti-Aims: Copied successfully!")
end

local function MoveAA()
	ui.set(pitch, pitch_value)
	ui.set(yawbase, yawbase_value)
	ui.set(yaw, yaw_value)
	ui.set(yawnum, yawnum_value)
	ui.set(yawjitter, yawjitter_value)
	ui.set(yawjitternum, yawjitternum_value)
	ui.set(yawwhilerunning, yawwhilerunning_value)
	ui.set(yawwhilerunningnum, yawwhilerunningnum_value)
	ui.set(fakeyaw, fakeyaw_value)
	ui.set(fakeyawnum, fakeyawnum_value)
	ui.set(edgeyaw, edgeyaw_value)
	ui.set(freestanding, freestanding_value)
	ui.set(freestanding_real_yawnum, freestanding_real_yawnum_value)
	ui.set(freestanding_fake_yawnum, freestanding_fakeyawnum_value)
	ui.set(crooked, crooked_value)
	ui.set(twist, twist_value)
	ui.set(fakelag_enabled, fakelag_enabled_value)
	ui.set(fakelag_triggers, fakelag_triggers_value)
	ui.set(fakelag_amount, fakelag_amount_value)
	ui.set(fakelag_variance, fakelag_variance_value)
	ui.set(fakelag_limit, fakelag_limit_value)
	ui.set(fakelag_whileshooting, fakelag_whileshooting_value)
	ui.set(freestanding_ignoreduck, freestanding_ignoreduck_value)
	ui.set(fakelag_resetonbhop, fakelag_resetonbhop_value)
	ui.set(fakelag_resetonstandstill, fakelag_resetonstandstill_value)
	ui.set(slowmotion, slowmotion_value)
	ui.set(fixlegmovement, fixlegmovement_value)
	client.log("Anti-Aims: Pasted successfully!")
end

function dump(o)
	if type(o) == "table" then local s = ""
	   for k,v in pairs(o) do
			if type(k) ~= "number" then k = '"'..k..'"' end
			s = s .. dump(v) .. ", "
	   end
	   return s
	else return tostring(o) end
end

local function has_value(tab, val)
    for index, value in ipairs(tab) do
        if value == val then
            return true
        end
    end
    return false
end

local cAct = { "Visuals", "Anti-aims" }
local cur_action = ui.new_multiselect("MISC", "Settings", "Copy Actions", cAct)

local function callback(val)
	local act = ui_get(val)
	for i = 1, table.getn(act) do
		local val = act[i]
		if val == cAct[1] then CopyVisuals() end
		if val == cAct[2] then CopyAA() end 
	end
end

local function doAction()
	if isCopiedESP == 1 or isCopiedAA == 1 then
		
		local act = ui_get(cur_action)
		client.log("Executions: ", dump(act))

		if isCopiedESP == 1 then MoveVisuals() end
		if isCopiedAA == 1 then MoveAA() end

		isCopiedESP, isCopiedAA = 0, 0
		ui.set(cur_action, {})
	else client.log("Error Pasting: No active Actions") end
end

local doButton = ui.new_button("MISC", "Settings", "Do Action", doAction)
ui.set_callback(cur_action, callback)